
textos_español = {
    # Traducciones literales
    'aceptar': 'Aceptar',
    'actualizacion': 'Actualizacion',
    'actualizando': 'Actualizando',
    'actualizar': 'Actualizar',
    'agregar': 'Agregar',
    'agregar nueva descarga': 'Agregar nueva descarga',
    'agregar a la cola': 'Agregar a la cola',
    'añadir': 'Añadir',
    'añadir a la cola': 'Añadir a la cola',
    'año': 'Año',
    'apagar': 'Apagar',
    'apagar-al-finalizar': 'Apagar al finalizar',
    'aplicacion': 'Aplicacion',
    'actualizar_url': 'Actualizar url',
    'archivo': 'Archivo',
    'archivos': 'Archivos',
    'bajo consumo': 'Bajo comsumo',
    'borrar datos': 'Borrar datos',
    'calculando': 'Calculando',
    'cambiar': 'Cambiar',
    'cambiar carpeta': 'Cambiar carpeta',
    'cambiar nombre': 'Cambiar nombre',
    'cancelar': 'Cancelar',
    'carpeta cambiada': 'Carpeta cambiada',
    'casi termina': 'Casi termina',
    'cerrar': 'Cerrar',
    'cola':'Cola',
    'completado': 'Completado',
    'comprobar': 'Comprobar',
    'confirmar': 'Confirmar',
    'copiado al portapapeles': 'Copiado al portapapeltes',
    'descargar': 'Descargar',
    'descargado': 'Descargado',
    'descargando': 'Descargando',
    'Desea_apagar': 'Desea apagar al finalizar la descarga?',
    'Desea_ejecutar': 'Desea ejecutar el archivo al finalizar la descarga?',
    'detalles': 'Detalles',
    'detener': 'Detener',
    'detenido': 'Detenido',
    'dia': 'Dia',
    'disponible': 'Disponible',
    'eliminar': 'Eliminar',
    'ejecutar-al-finalizar': 'Ejecutar al finalizar',
    'en espera': 'En espera',
    'enhorabuena': 'Enhorabuena',
    'esperando': 'Esperando',
    'estado': 'Estado',
    'extencion': 'Extension',
    'extenciones': 'Extenciones',
    'fecha': 'Fecha',
    'finalizado': 'Finalizado',
    'hilos': 'Hilos',
    'hora': 'Hora',
    'iniciar': 'Iniciar',
    'instalar': 'Instalar',
    'la': 'La',
    'limpiar cola': 'Limpiar Cola',
    'limitar-velocidad': 'Limitar Velocidad',
    'lista actualizada': 'Lista actualizada',
    'minuto': 'Minuto',
    'nombre': 'Nombre',
    'nueva descarga disponible': 'Nueva descarga disponible',
    'numero invalido': 'Numero invalido',
    'pausar': 'Pausar',
    'pausado': 'Pausado',
    'particulas': 'Particulas',
    'reanudar': 'Resumir',
    'redescargar': 'Redescargar',
    'reiniciar': 'Reiniciar',
    'remover de la cola': 'Remover de la cola',
    'segundo': 'Segundo',
    'si': 'Si',
    'tamaño': 'Tamaño',
    'tiempo restante': 'Tiempo restante',
    'tipo': 'Tipo',
    'velocidad': 'Velocidad',


    
    # Titulo principal
    'title': 'Acelerador de descargas',

    # Botones
    'btn-nueva_descarga': 'Nueva descarga',
    'btn-cambiar_carpeta': 'Cambiar carpeta',

    # EstaDos de los hilos
    'status_hilo[iniciando]': 'Hilo {}: Iniciando...',
    'status_hilo[conectando]': 'Hilo {}: Conectando...',
    'status_hilo[pausado]': 'Hilo {}: Pausado',
    'status_hilo[cancelado]': 'Hilo {}: Cancelado',
    'status_hilo[reconectando]': 'Hilo {}: Reintentando...',
    'status_hilo[descargando]': 'Hilo {}: Descargando...',
    'status_hilo[finalizado]': 'Hilo {}: Finalizado',

    # Configuraciones
    'title-configuraciones': 'Configuraciones',
    'config-hilos': 'Hilos: {}',
    'config-idioma': 'Idioma:',

    # GUI's
    'gui-desea_abrir_la_carpeta': "La descarga ah finalizado\n\nDesea ir a la carpeta de las descargas?",
    'gui-url no sirve': "El URL a dejado de funcionar\n\nActualize la URL o intente mas tarde",
    "gui-error inesperado":"A ocurrido un error inesperado\nCompruebe su conexion a internet\n\nDesea volver a intentarlo?",
    'gui-desea descargar la actualizacion': 'Hay una nueva actualizacion disponible\n\nDesea agregar a la lista de descargas?',
    'gui-desea borrar el elemento': '¿Desea borrar el elemento seleccionado!?',
    'gui-desea borrar los elementos': '¿Desea borrar los elementos seleccionados!?',
    'gui-carpeta cambiada con exito': 'Carpeta para guardar archivos\ncambiada con exito.',
    'gui-descarga eliminada': 'La descarga ha sido eliminada',
    'gui-descarga en curso':'La descarga esta en curso',
    'gui-descarga en cola':'La descarga esta en la cola',
    'gui-descarga iniciada': 'La descarga ha iniciado...',
    'gui-cola de descarga completada':'La cola de descargas ha finalizado',
    'gui-nombre del archivo':'Nombre del archivo',
    'gui-solo una descarga': 'Opcion solo valida para\nuna descarga a la vez...',
    'gui-cancelar descarga': '¿Desea cancelar la descarga en curso?',
    'gui-no se puede reanudar': 'La descarga no se puede reanudar:\nEl link no permite reanudar la descarga',

    # Downloader
    
    'title_hilos': 'Hilos de descarga',

    # Estados de los hilos
    'descripcion-peso': 'Peso: {}',
    'descripcion-numero_hilos': 'Numero de hilos: {}',
    'descripcion-state[esperando]': 'Estado: Esperando...',
    'descripcion-state[conectando]': 'Estado: Conectando...',
    'descripcion-state[descargando]': 'Estado: Descargando...',
    'descripcion-state[disponible]': 'Estado: Disponible',
    'descripcion-state[error]': 'Estado: Error',
    'descripcion-state[url invalida]': 'Estado: URL Invalida',
    'descripcion-state[tiempo agotado]': 'Estado: Tiempo de espera agotado',
    'descripcion-state[reintentando]': 'Estado: Reintentando',
    'descripcion-state[finalizado]': 'Estado: Finalizado',
    'descripcion-state[error internet]': 'Estado: Compruebe su conexion a internet',
    'descripcion-state[trajo un html]': 'Estado: Capturó un HTML (Error)',

}


#             ------------------       -----------------------        -------------------        --------------------


textos_ingles = {
    # traducciones literales
    'aceptar': 'Accept',
    'actualizacion': 'Update',
    'actualizando': 'Updating',
    'actualizar': 'Update',
    'agregar': 'Add',
    'agregar nueva descarga': 'Add new download',
    'añadir a la cola': 'Add to queue',
    'agregar a la cola': 'Add to queue',
    'añadir': 'Add',
    'año': 'Year',
    'apagar': 'Turn off',
    'apagar-al-finalizar': 'Turn off at the end',
    'aplicacion': 'Application',
    'archivo': 'File',
    'archivos': 'Files',
    'actualizar_url': 'Update url',
    'bajo consumo': 'Low consumption',
    'borrar datos': 'Delete data',
    'calculando': 'Calculating',
    'cambiar': 'Change',
    'cambiar carpeta': 'Change Folder',
    'cambiar nombre': 'Change name',
    'cancelar': 'Cancel',
    'carpeta cambiada': 'Folder changed',
    'casi termina': 'it\'s almost over',
    'cerrar': 'Close',
    'cola':'Queue',
    'completado': 'Finished',
    'comprobar': 'Check',
    'confirmar': 'Confirm',
    'copiado al portapapeles': 'Copied to clipboard',
    'descargar': 'Download',
    'descargado': 'Downloaded',
    'descargando': 'Downloading',
    'Desea_apagar': 'Do you want to turn off at the end of the download?',
    'Desea_ejecutar': 'Do you want execute this file at the end of the download?',
    'detalles': 'Details',
    'dia': 'Day',
    'disponible': 'Disponible',
    'eliminar': 'Delete',
    'ejecutar-al-finalizar': 'Execute at the end',
    'en espera': 'on hold',
    'enhorabuena': 'Congratulations',
    'esperando': 'Waiting',
    'estado': 'State',
    'extencion': 'Extension',
    'extenciones': 'Extensions',
    'fecha': 'Date',
    'finalizado': 'Finished',
    'hilos': 'Threads',
    'hora': 'Hour',
    'iniciar': 'init',
    'instalar': 'Install',
    'la': 'The',
    'limpiar cola': 'Clear Queue',
    'limitar-velocidad': 'Limit Speed',
    'lista actualizada': 'List updated',
    'minuto': 'Minute',
    'nombre': 'Name',
    'nueva descarga disponible': 'New download available',
    'numero invalido': 'Invalid number',
    'pausar': 'Pause',
    'pausado': 'Paused',
    'particulas': 'Particles',
    'reanudar': 'Resume',
    'redescargar': 'Re-download',
    'reiniciar': 'Reset',
    'remover de la cola': 'Remove of the Queue',
    'segundo': 'Second',
    'si': 'Yes',
    'tiempo restante': 'Remaining time',
    'tamaño': 'Size',
    'tipo': 'Type',
    'velocidad': 'Velocity',


    # Titulo principal
    'title': 'Downloads manager',

    # Botones
    'btn-nueva_descarga': 'New download',
    'btn-cambiar_carpeta': 'Change dir',

    # Estados de los hilos
    'status_hilo[iniciando]': 'Thread {}: Starting...',
    'status_hilo[conectando]': 'Thread {}: Connecting...',
    'status_hilo[pausado]': 'Thread {}: Paused',
    'status_hilo[cancelado]': 'Thread {}: Canceled',
    'status_hilo[reconectando]': 'Thread {}: Retrying...',
    'status_hilo[descargando]': 'Thread {}: Downloading...',
    'status_hilo[finalizado]': 'Thread {}: Finalized',

    # Configuraciones
    'title-configuraciones': 'Configurations',
    'config-hilos': 'Threads: {}',
    'config-idioma': 'Lenguaje:',

    #GUI's
    'gui-desea_abrir_la_carpeta': "Download Finished\n\nDo you want open the downloads dir?",
    'gui-url no sirve': "The URL it's not working\n\nUpdate it or try again later.",
    "gui-error inesperado": "An unexpected error has occurred\n\nDo you want to try again?",
    'gui-desea descargar la actualizacion': 'New update available\n\nDo you want to download it?',
    'gui-desea borrar los elementos': 'Do you want delete this downloads?!',
    'gui-desea borrar el elemento': 'Do you want delete this download?!',
    'gui-carpeta cambiada con exito': 'folder changed\nsuccessfully',
    'gui-descarga eliminada': 'Download deleted',
    'gui-descarga en curso':'Download in progress',
    'gui-descarga en cola':'Download in the Queue',
    'gui-descarga iniciada':'Download started...',
    'gui-cola de descarga completada':'The download Queue it\'s finished',
    'gui-nombre del archivo':'Name of the file',
    'gui-solo una descarga': 'Opcion only valid for\none download at a time...',
    'gui-cancelar descarga': 'Do you want cancel the current download?',
    'gui-no se puede reanudar': 'This download can\'t continue:\nIs not alowed to resume',

    # Downloader
    'title_hilos': 'Downloads threads',

    # Estados de los hilos
    'descripcion-peso': 'Size: {}',
    'descripcion-numero_hilos': 'number of threads: {}',
    'descripcion-state[esperando]': 'State: Waiting...',
    'descripcion-state[conectando]': 'State: Connecting...',
    'descripcion-state[descargando]': 'State: Downloading...',
    'descripcion-state[disponible]': 'State: Available',
    'descripcion-state[error]': 'State: Error',
    'descripcion-state[url invalida]': 'State: Invalid URL',
    'descripcion-state[tiempo agotado]': 'State: Waiting time out',
    'descripcion-state[reintentando]': 'State: Retrying',
    'descripcion-state[finalizado]': 'State: Finalized',
    'descripcion-state[error internet]': 'State: Connection Error',
    'descripcion-state[trajo un html]': 'State: Is an HTML (Error)',

}

idiomas = {
    'español': textos_español,
    'ingles': textos_ingles
}